### ISSUE TITLE
Add support for environment variables in YAML's schema_dir

### ISSUE THREAD

**Issue by baltzell** [JeffersonLab/clas12-offline-software#843]
In org.jlab.io.clara.HipoToHipoWriter.   For simplification and to avoid unnecessarry user customization and errors in YAML files and instead be able to put just, for example:

```
configuration:
    io-services:
        writer:
            schema_dir:  "$CLARA_HOME/plugins/clas12/etc/bankdefs/hipo4/singles/dst"
```

A side note .... does recon-util even support schema_dir?  Doesn't look like it.
